version: '3'
services:
  node:
    build: node
    image: node-my-dev:1.0
    container_name: node
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "3000:3000"
    command: npm run dev
