FROM node:13.10-stretch-slim
# ENV NODE_ENV=development
WORKDIR /app
# RUN npm init -y
# RUN npm install react react-dom next  @material-ui/core
# RUN npm install --save-dev typescript @types/react @types/node jest