FROM node:13.10-stretch-slim
WORKDIR /app
RUN apt update && apt upgrade && apt install -y git vim
# ENV NODE_ENV=development
# RUN npm init -y
# RUN npm install react react-dom next  @material-ui/core
# RUN npm install --save-dev typescript @types/react @types/node jest
